protocol device {
}

protocol direct {
  ipv4;
  interface "eth*";
}

protocol kernel {
  ipv4 {
    export where source != RTS_DEVICE;
  };
}

protocol ospf v2 {
  ipv4 {
    import all;
    export none;
  };
  area 0 {
    interface "eth*";
  };
}