protocol device {
}

protocol direct {
  ipv4;
  interface "eth*";
}

protocol kernel {
  ipv4 {
    export where source != RTS_DEVICE;
  };
}

protocol rip {
  ipv4 {
    import all;
    export all;
  };
  interface "eth*";
}