protocol device {
}

protocol direct {
  ipv4;
  interface "eth*";
}

protocol kernel {
  ipv4 {
    export where source != RTS_DEVICE;
  };
}

protocol bgp r2 {
  local as 100;
  neighbor 10.0.12.12 as 100;
  ipv4 {
    import all;
    export all;
    next hop self;
  };
}

protocol bgp r5 {
  local as 100;
  neighbor 10.0.15.15 as 300;
  ipv4 {
    import all;
    export all;
  };
}