protocol device {
}

protocol direct {
  ipv4;
  interface "eth*";
}

protocol kernel {
  ipv4 {
    export where source != RTS_DEVICE;
  };
}

protocol bgp r1 {
  local as 100;
  neighbor 10.0.12.11 as 100;
  ipv4 {
    import all;
    export all;
    next hop self;
  };
}

protocol bgp r3 {
  local as 100;
  neighbor 10.0.23.13 as 200;
  ipv4 {
    import all;
    export all;
  };
}