protocol device {
}

protocol direct {
  ipv4;
  interface "eth*";
}

protocol kernel {
  ipv4 {
    export where source != RTS_DEVICE;
  };
}

protocol bgp r2 {
  local as 200;
  neighbor 10.0.23.12 as 100;
  ipv4 {
    import all;
    export all;
  };
}

protocol bgp r4 {
  local as 200;
  neighbor 10.0.34.14 as 200;
  ipv4 {
    import all;
    export all;
    next hop self;
  };
}