protocol device {
}

protocol direct {
  ipv4;
  interface "eth*";
}

protocol kernel {
  ipv4 {
    export where source != RTS_DEVICE;
  };
}

protocol bgp r3 {
  local as 200;
  neighbor 10.0.34.13 as 200;
  ipv4 {
    import all;
    export all;
    next hop self;
  };
}

protocol bgp r5 {
  local as 200;
  neighbor 10.0.45.15 as 300;
  ipv4 {
    import all;
    export all;
  };
}