protocol device {
}

protocol direct {
  ipv4;
  interface "eth*";
}

protocol kernel {
  ipv4 {
    export where source != RTS_DEVICE;
  };
}

protocol bgp r4 {
  local as 300;
  neighbor 10.0.45.14 as 200;
  ipv4 {
    import all;
    export all;
  };
}

protocol bgp r1 {
  local as 300;
  neighbor 10.0.15.11 as 100;
  ipv4 {
    import all;
    export all;
  };
}